### ISSUE TITLE
Map Sidebar needs to reflect configuration file

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-app-info-mapper-ng#104]
The sidebar right now just displays 'layers', and does not do a good job of showing layerViewGroups and layerViews.

**Comment by smalers** [comment]
More specifically, each GeoLayerViewGroup should have a display area similar to the ***Basemap Layers***. Controls specific to the group can be shown at the top of each area, but should ideally be minimized so that the focus is on the layers in the group.  The order should be as in the configuration file with group at top being drawn on top.  The name shown in the highlighted title should be the GeoLayerViewGroup.name.  The description can be shown under that to describe the group, but may want a way to hide/minimize the description.

It may still make sense to have some controls above all groups, similar to what is included now, with  "hide all groups" and "hide all layers",  However, if we do a good job displaying the maps in the first place, users may typically just make minor changes.

**Comment by Nightsphere** [comment]
The sidebar reflects the config file now as far as what it shows in what order. It still doesn't separate by viewGroup, but that is
another issue (Issue #119). Closing this issue.
