### ISSUE TITLE
Update Angular to latest stable version

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#191]
See issue #190 about making an official release.  We need to decide whether to stay with current version of Angular that we are using or move to a newer version.  The release notes should be clear on what version stack we are using when we make a major release.

I am not asking or recommending that we update versions now, but only that we plan for it.  All third-party components such as ChartJS will need to be compatible.  The update could be done an a branch where the version update is the ONLY change in that branch (no new features).  We want to do no harm.  Hopefully an Angular update does help, such as improving performance.

**Comment by Nightsphere** [comment]
The Info Mapper was upgraded to Angular version 9. This is actually not the latest stable build, as Angular 10 came out within
the last week, but seemed a little too new to try to upgrade to, even if it is stable. Sofia helped with the upgrade since her chart
example app uses Angular 9 as well, so upgrading was not as difficult as expected. Testing was done to ensure the update did
not introduce any other bugs or third party package issues, but just to be safe, a copy of the old info mapper version was kept
just in case.

**Comment by Nightsphere** [comment]
After continued testing of the app, everything seems to be in working order. Perhaps the app can be upgraded again, but as
mentioned previously, the last stable build was within the last week, so this could be done further on down the line. Closing
the issue.
