### ISSUE TITLE
Markdown tables are not formatted nicely

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#212]
**This may be something that Sofia can address in her work.**

I have added some tables in Markdown documents.  However, they do not render nicely.  the alignment and horizontal layout of the tables makes the content difficult to read.  An example of a Markdown file is the [Poudre counties layer](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/workflow/BasinEntities/Physical-Counties/layers/counties.md).  Note that this markdown displays nicely in GitHub but not in Showdown.

So... I either need to be told how to format my Markdown to work well with Showdown and work nice, or we need to figure out another way to fix.

![image](https://user-images.githubusercontent.com/6448274/88739927-03f45600-d0f9-11ea-8fa8-3c1520602a36.png)

**Comment by gsofia23** [comment]
Example implemented in the Angular visualization application. Solution consists of importing Showdown with certain options configured.
`imports: [ ShowdownModule.forRoot({emoji: true, noHeaderId: true, flavor: 'github'}) ]`

**Comment by gsofia23** [comment]
The solution above does format markdown as a table but renders without style. No styling is applied by default with Showdown so that it doesn't interfere with other styling libraries such as Bootstrap. 

Because Showdown generates simple HTML, the best practices for styling appearances will be through CSS.  The generated Markdown can be wrapped with an id and style. 

The style can also be specified by incorporating straight into the Markdown file using a `<style>` tag.
The following CSS can be placed within the markdown source or within respected css file to resolve table formatting.

`<style> 
    table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
    display: block;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #ededed
  }
</style>`

In order to control of specific elements, an extension is needed to create "new syntax" for the file.

**Comment by smalers** [comment]
We need a working example in the Angular demo application.

**Comment by Nightsphere** [comment]
The above CSS has been incorporated into the `styles.css` file in the Info Mapper, and tables are now formatted correctly in the
Info Mapper. Closing the issue.
