### ISSUE TITLE
Showdown not handling end of line well

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#225]
**I am entering this issue for InfoMapper but would like Sofia to figure it out in the demonstration application first and coordinate with Josh.**

The Showdown output is not properly handling newlines in the source.  The resulting HTML has partial lines that break prematurely.  See the [Poudre Trails](http://poudre.openwaterfoundation.org/0.2.1/#/map/entities-trails) page.   Click on the information button for the Poudre Trails layer, next to the on/off slider.  Here are issues to be resolved:

* Paragraph content should generally fill the width of the page.  I prefer left justified and not both-justified.  The current output seems to be breaking when I have a newline in the Markdown file.   I tend to use newlines because I want the file in GitHub to allow diffs on lines, not one big blob.
* The blank line between in front of the ***Map Creation Workflow*** heading is less than other sections.  Maybe it is also related to newlines?  I tried to insert an extra line.

See the [source Markdown](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/workflow/BasinEntities/Recreation-Trails/layers/trails-fortcollins-doc/trails-fortcollins.md) file.

**Comment by gsofia23** [comment]
By default, Showdown would not behave in this way with partial lines that prematurely break. Because of the use of GFM flavor, the option ``simpleLineBreaks`` is activated. To fix this deactivation is required. 

Solution: Disable `simpleLineBreaks`

Setting this option locally:
`<showdown [options]="{simpleLineBreaks: false}">
    * a
    * b
    * c
</showdown>`

Setting this option globally: 
` ShowdownModule.forRoot({noHeaderId: true, openLinksInNewWindow: true, smartIndentationFix: true, simpleLineBreaks: false, flavor: 'github'}),`

Example updated in demo application for reference.

**Comment by Nightsphere** [comment]
I have added the simpleLineBreaks option and the markdown should be working as desired now. Thanks to Sofia for finding it. Closing the issue.
