### ISSUE TITLE
Menus and submenus need enable property

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#85]
The latest push has `enabled` property on submenus.  However, I did not have in my `app-config.json` file.  The behavior in this case was that no submenus showed.  Also, setting to `false` does not seem to work.  The behavior should be as follows:

* `enabled` should default to `true` if not in the config file
* the property should be a boolean rather than a string if possible
* a value of `false` should still display the menu but it should be grayed out - this will allow new features to be laid out for demonstration purpose and functionality filled in
* to not show a menu, a property `visible` should be added with default `true` and `false` will not display the menu item at all - this is lower priority

**Comment by Nightsphere** [comment]
I just pushed for this issue. The enabled property has now been implemented so that it doesn't
need to be included, and defaults to `true`. Only saying `enabled: "false"` will gray out the 
button and nothing will happen when clicked.

`visible` has also been implemented. Default is all menus will be visible, unless `visible: "false"`
is added to the menu in the config file. I would close this but first wanted to check about the use
of the true and false values as strings and not booleans. I was used to having to deal with
properties as strings because that's how the GeoProcessor created them, but since the
app-config file isn't, then it's okay to make them booleans instead?

If so, it'll take 5 minutes to update this and I'll do a new push and close the issue.

**Comment by Nightsphere** [comment]
After talking with Steve, a new implementation has been added for having the enabled property be set
as a boolean or a string. Either will work. Closing this issue.

**Comment by smalers** [comment]
The disabled menus need to have their appearance changed.  The graying of the background makes it look like the menu is actually selected.  A disabled menu should have the same background as normal, but the text should be greyed out, similar to the following from TSTool.  The following also shows menu separators, which I mentioned in another issue.

![image](https://user-images.githubusercontent.com/6448274/82526229-b48a1c00-9af0-11ea-9773-8e7ab8271e19.png)

**Comment by Nightsphere** [comment]
New changes were made and pushed. As of now the menus are appearing the correct way whether
visible and/or enabled. Closing the issue.
